### ISSUE TITLE
Issue with creating elixir test files

### ISSUE THREAD

**Issue by retip94** [paul-mannino/vscode-create-test-file#3]
You've made great work with this extension 👍 
But there is a problem to use it in Elixir language projects.
The problem with elixir is, that test files have different extensions than other files.
For example:
filename.ex
filename.test.exs

If there would be an option that extension is not automatically added, but we could just add it in the file suffix, that would solve the problem.
Or adding some variable to set test file extension would also be great.

**Comment by bhenderson-riparian** [comment]
hi, thanks for this extension. I have the same problem. I have a `.vue` file that I want the test extension to be `.js`

**Comment by paul-mannino** [comment]
Thanks for the feedback! Fixed by https://github.com/paul-mannino/vscode-create-test-file/pull/11
